name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.2'

      - name: Flutter Doctor
        run: flutter doctor -v
        working-directory: flutter_app

      - name: Install dependencies
        run: flutter pub get
        working-directory: flutter_app

      - name: Analyze
        run: flutter analyze --no-fatal-infos
        working-directory: flutter_app

      - name: Run tests
        run: flutter test
        working-directory: flutter_app

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Android (Gradle direct)
        run: |
          cd android
          ./gradlew.bat --no-daemon assembleDebug -x lint -x test
        working-directory: flutter_app

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: flutter_app/android/app/build/outputs/flutter-apk/app-debug.apk

      - name: Build Web
        run: flutter build web
        working-directory: flutter_app

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: flutter_app/build/web
